An error has occurred:
The machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.
Caused by: error

Trace:
entering func:test/CallTrace/Spec.hs:69:1-69:4
entering $fMyClassInOtherModule()_$cmyClassFuncInOtherModule:test/CallTrace/OtherModule.hs:23:3-23:26