An error has occurred:
The machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.
Caused by: error

Trace:
-> func:test/CallTrace/Spec.hs:78:1-78:4
-> nestedLinear2:test/CallTrace/Spec.hs:72:1-72:13
-> nestedLinear3:test/CallTrace/Spec.hs:73:1-73:13
-> nestedLinear4:test/CallTrace/Spec.hs:74:1-74:13
-> error