(Left An error has occurred:
'case' over a value of a built-in type failed with
'case 1' is out of bounds for the given number of branches: 0
Caused by: (con integer 1))